### ISSUE TITLE
[Bug]: Cant use img2img, fresh install

### ISSUE THREAD

**Issue by iChristGit** [sd-webui/stable-diffusion-webui#632] opened 2022-09-04 17:16 UTC
### What happened?

I just installed with the guide, getting an error anything related to img2img, text2img is fine, any idea whatsup?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
LDSR not found at path, please make sure you have cloned the LDSR repo to ./src/latent-diffusion/
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nahojjjen** [comment] 2022-09-04 18:53
I get the same issue
![bild](https://user-images.githubusercontent.com/8545451/188328933-c16c9a61-d6b0-4c55-8dd8-419a8362ae91.png)

**Comment by telemole** [comment] 2022-09-04 19:06
Complete reinstall of everything except the ckpt model file (since why bother) and I still get the same : 

sd                  | Traceback (most recent call last):
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd                  |     output = await app.blocks.process_api(
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
sd                  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
sd                  |     processed_input.append(block.preprocess(raw_input[i]))
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
sd                  |     x, mask = x["image"], x["mask"]
sd                  | TypeError: string indices must be integers

**Comment by iChristGit** [comment] 2022-09-04 19:50
Do you have that line ".conda\envs\ldo\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(" ?

**Comment by telemole** [comment] 2022-09-04 19:51
Yes I also have that!

sd                  | LatentDiffusion: Running in eps-prediction mode
sd                  | DiffusionWrapper has 859.52 M params.
sd                  | making attention of type 'vanilla' with 512 in_channels
sd                  | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
sd                  | making attention of type 'vanilla' with 512 in_channels
sd                  | /opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
sd                  |   warnings.warn(

**Comment by slashedstar** [comment] 2022-09-04 20:01
You need to go to editor mode, mask mode, draw any mask and go back to crop mode, voilá, it works again, its an old bug that got reintroduced somehow, thats the workaround.

**Comment by bbecausereasonss** [comment] 2022-09-04 20:04
File "C:\Users\chlyw\.conda\envs\ldo\lib\site-packages\gradio\processing_utils.py", line 28, in decode_base64_to_image    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by telemole** [comment] 2022-09-04 20:17
> You need to go to editor mode, mask mode, draw any mask and go back to crop mode, voilá, it works again, its an old bug that got reintroduced somehow, thats the workaround.

I've tried this and after I do so I get this! 

sd                  | Exception processing job JobInfo(inputs=('fantasy landscape', 'Crop', 0, 3, 16, 'k_lms', [1, 4, 5, 6, 7], 'RealESRGAN_x4plus', 1, 5, 0.75, None, 512, 512, 0, <PIL.Image.Image image mode=RGBA size=512x512 at 0x7FF3367ADA60>, {'image': <PIL.Image.Image image mode=RGBA size=1024x512 at 0x7FF3367AD9D0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1024x512 at 0x7FF3367AD610>}, None), func=<function img2img at 0x7ff227b3da60>, session_key='"612662762a8348adb308bf363ef7c1fa"', job_token=0, images=[], should_stop=<threading.Event object at 0x7ff3367ad8e0>, job_status="Error: argument of type 'int' is not iterable", finished=False, removed_output_idxs=[0]): argument of type 'int' is not iterable
sd                  | Traceback (most recent call last):
sd                  |   File "/sd/frontend/job_manager.py", line 232, in _call_func
sd                  |     outputs = job_info.func(*job_info.inputs, job_info=job_info)
sd                  |   File "scripts/webui.py", line 1234, in img2img
sd                  |     prompt_matrix = 0 in toggles
sd                  | TypeError: argument of type 'int' is not iterable
sd                  |
sd                  | Traceback (most recent call last):
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd                  |     output = await app.blocks.process_api(
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 645, in process_api
sd                  |     output = self.postprocess_data(fn_index, predictions, state)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 611, in postprocess_data
sd                  |     block.postprocess(prediction_value)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 673, in postprocess
sd                  |     return self.round_to_precision(y, self.precision)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 563, in round_to_precision
sd                  |     return float(num)
sd                  | ValueError: could not convert string to float: '625b41e7d610470c8a8454a32021f8cb'

**Comment by telemole** [comment] 2022-09-04 20:32
> You need to go to editor mode, mask mode, draw any mask and go back to crop mode, voilá, it works again, its an old bug that got reintroduced somehow, thats the workaround.

have tried this a few different ways and I get one of the two error streams above :(

**Comment by slashedstar** [comment] 2022-09-04 22:07
Oh, I also get this `ValueError: could not convert string to float` a couples of times, not sure how to reproduce it tho, this version introduced a lot of bugs 😬

**Comment by telemole** [comment] 2022-09-04 23:10
again - complete rebuild - whatever they did in the last hour, now working for me with the 'go to mask, draw, go to crop' fix...

**Comment by helgur** [comment] 2022-09-04 23:44
> You need to go to editor mode, mask mode, draw any mask and go back to crop mode, voilá, it works again, its an old bug that got reintroduced somehow, thats the workaround.

Whenever I click the "Mask" radio select button under "Image Editor Mode" in "Editor options" I get a javascript error in the browser console and the whole app stops working:

`Uncaught (in promise) TypeError: t is null
    K http://localhost:7860/assets/index.4ddf74a5.js:3853
    p http://localhost:7860/assets/index.037cda16.js:142
    update_slot_base http://localhost:7860/assets/index.4ddf74a5.js:126
    p http://localhost:7860/assets/index.037cda16.js:40
    update http://localhost:7860/assets/index.4ddf74a5.js:615
    flush http://localhost:7860/assets/index.4ddf74a5.js:582
    promise callback*schedule_update http://localhost:7860/assets/index.4ddf74a5.js:540
    make_dirty http://localhost:7860/assets/index.4ddf74a5.js:1071
    ctx http://localhost:7860/assets/index.4ddf74a5.js:1109
    3 http://localhost:7860/assets/index.4ddf74a5.js:6347
    set http://localhost:7860/assets/index.4ddf74a5.js:1193
    update http://localhost:7860/assets/index.4ddf74a5.js:1201
    update http://localhost:7860/assets/index.4ddf74a5.js:3983
    onmessage http://localhost:7860/assets/index.4ddf74a5.js:7810
    fn http://localhost:7860/assets/index.4ddf74a5.js:7796
    handle_mount http://localhost:7860/assets/index.4ddf74a5.js:6522
    bubble http://localhost:7860/assets/index.4ddf74a5.js:527
    bubble http://localhost:7860/assets/index.4ddf74a5.js:527
    change_handler http://localhost:7860/assets/index.3a6ac284.js:440
    createEventDispatcher http://localhost:7860/assets/index.4ddf74a5.js:506
    createEventDispatcher http://localhost:7860/assets/index.4ddf74a5.js:505
    update http://localhost:7860/assets/index.3a6ac284.js:242
    update http://localhost:7860/assets/index.4ddf74a5.js:611
    flush http://localhost:7860/assets/index.4ddf74a5.js:582
    promise callback*schedule_update http://localhost:7860/assets/index.4ddf74a5.js:540
    make_dirty http://localhost:7860/assets/index.4ddf74a5.js:1071
    ctx http://localhost:7860/assets/index.4ddf74a5.js:1109
    switch_instance_value_binding http://localhost:7860/assets/index.4ddf74a5.js:5192
    switch_instance_value_binding http://localhost:7860/assets/index.4ddf74a5.js:5030
    ctx http://localhost:7860/assets/index.4ddf74a5.js:1107
    radio_value_binding http://localhost:7860/assets/index.3a6ac284.js:436
    radio_value_binding http://localhost:7860/assets/index.3a6ac284.js:300
    ctx http://localhost:7860/assets/index.4ddf74a5.js:1107
    input_change_handler http://localhost:7860/assets/index.3a6ac284.js:227
    listen http://localhost:7860/assets/index.4ddf74a5.js:230
    m http://localhost:7860/assets/index.3a6ac284.js:80
    m http://localhost:7860/assets/index.3a6ac284.js:170
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.3a6ac284.js:329
    m http://localhost:7860/assets/Block.d349039f.js:45
    m http://localhost:7860/assets/Block.d349039f.js:106
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.3a6ac284.js:393
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:5066
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:4927
    m http://localhost:7860/assets/index.4ddf74a5.js:4855
    m http://localhost:7860/assets/index.4ddf74a5.js:4971
    m http://localhost:7860/assets/index.955bfbfb.js:22
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:5066
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:4927
    m http://localhost:7860/assets/index.4ddf74a5.js:4855
    m http://localhost:7860/assets/index.4ddf74a5.js:4971
    m http://localhost:7860/assets/index.11e45c37.js:26
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:5066
    mount_component http://localhost:7860/assets/index.4ddf74a5.js:1039
    m http://localhost:7860/assets/index.4ddf74a5.js:4927
    m http://localhost:7860/assets/index.4ddf74a5.js:4855
    m http://localhost:7860/assets/index.4ddf74a5.js:4971
    m http://localhost:7860/assets/index.c149ecfb.js:222
index.4ddf74a5.js:3853:3697
`

**Comment by dogarrowtype** [comment] 2022-09-05 00:27
> You need to go to editor mode, mask mode, draw any mask and go back to crop mode, voilá, it works again, its an old bug that got reintroduced somehow, thats the workaround.

Getting the same issue tonight, and this workaround fixes it.

**Comment by TristanMorelle** [comment] 2022-09-05 09:21
#664

**Comment by mchaker** [comment] 2022-09-06 14:47
There is a fix in the `img2img-fix` branch. See comment: https://github.com/hlky/stable-diffusion-webui/issues/664#issuecomment-1237025304

**Comment by codedealer** [comment] 2022-09-07 22:52
Branch has been merged to master

**Closed by codedealer** 2022-09-07 22:52 UTC
Labels: bug
