### ISSUE TITLE
[Bug]: img2img returns error, txt2img works fine.

### ISSUE THREAD

**Issue by njalooo** [sd-webui/stable-diffusion-webui#839] opened 2022-09-08 15:05 UTC
### What happened?

I tried refining an image i got from txt2img, and upon generating it this happened. It also doesn't work otherwise, with or without mask. It always throws the same error.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Custom settings

```shell
I have activated cpu offloading and optimized mode.
```

### Relevant log output

```shell
[MemMon] Recording max memory usage...

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████| 38/38 [00:57<00:00,  1.52s/it]
Exception processing job JobInfo(inputs=('girl holding sword in hand, seen from front, highly detailed,light effects, painting by mike dargas,gaston bussiere, craig mullins, greg rutkowski, yoji shinkawa.', 'Mask', <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F4995734DC0>, {'image': <PIL.Image.Image image mode=RGB size=512x512 at 0x7F499571C0D0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x7F4995734A60>}, 1, 4, 50, 'k_lms', [1, 4, 5, 6, 7, 10], 'RealESRGAN_x4plus', 1, 5, 0.75, '57457734643456', 512, 512, 0, None), func=<function img2img at 0x7f48ac4ce4c0>, session_key='"b755bbe8fd3d4b2cb1b05d4df1c703a1"', job_token=0, images=[], should_stop=<threading.Event object at 0x7f4995734be0>, job_status='Error: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same', finished=False, removed_output_idxs=[0]): Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same
Traceback (most recent call last):
  File "/home/caramon/stablediffusionGUI/stable-diffusion-webui/frontend/job_manager.py", line 232, in _call_func
    outputs = job_info.func(*job_info.inputs, job_info=job_info)
  File "scripts/webui.py", line 1445, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 974, in process_images
    cropped_faces, restored_faces, restored_img = GFPGAN.enhance(original_sample[:,:,::-1], has_aligned=False, only_center_face=False, paste_back=True)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/caramon/stablediffusionGUI/stable-diffusion-webui/src/gfpgan/gfpgan/utils.py", line 108, in enhance
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torchvision/models/_utils.py", line 63, in forward
    x = module(x)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same

Traceback (most recent call last):
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "/home/caramon/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: '34e968bc905946d3800cbecaac633f52'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment] 2022-09-08 15:54
Don't put upscalers on CPU. Duplicate of of #702

You can share additional information there.

**Closed by codedealer** 2022-09-08 15:54 UTC
Labels: bug
