### ISSUE TITLE
[Bug]: Strange Mask Behaivour in Dev version

### ISSUE THREAD

**Issue by entusiastaIA** [sd-webui/stable-diffusion-webui#960] opened 2022-09-10 11:49 UTC
### What happened?

I am consistently getting this problem with masking since today morning (3 hours ago). The masked area in the source image does not fits the area of the image that gets masked in the output image... is kind of like the mask it self got resized and placed in a different place.

You can see it in the picture, the intended masked area and the output image the shadow that has been altered with the same shape but different size and place. Also I have double checked that source image and output were both same dimensions (704x384)

![Captura](https://user-images.githubusercontent.com/113212323/189481939-8e6aa0fa-c969-45bc-8991-e860d11beb0e.PNG)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment] 2022-09-10 11:57
Duplicate of #495

**Closed by codedealer** 2022-09-10 11:57 UTC
Labels: bug
