### ISSUE TITLE
[Bug]: k_euler_a and k_dpm_2_a produce different result with same seed depending on batch size

### ISSUE THREAD

**Issue by jokkebk** [sd-webui/stable-diffusion-webui#1350] opened 2022-09-28 09:31 UTC
### What happened?

Not sure if this is a bug or a feature, and likely not limited to webui, but I observed that at least two sampling methods, k_euler_a and k_dpm_2_a, produce different result with exactly same settings and seed, depending on the batch size.

Example settings to reproduce:

batch_size: 1
cfg_scale: 7.5
ddim_eta: 0
ddim_steps: 25
height: 768
n_iter: 1
prompt: cat
sampler_name: k_euler_a
seed: 1
target: txt2img
toggles:
- 1
- 2
- 3
- 4
- 5
width: 512

Generate a cat with these. Now change batch size to 2 and regenerate. The seed 1 image should be quite completely different.

Could not replicate with k_lms for example, so it seems the amount of images is affecting a RNG or something in the process with these two _a samplers.

GPU is RTX 2080 Super with 8 GB of RAM, if that makes a difference.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment] 2022-09-28 09:34
Duplicate of #1287

**Comment by jokkebk** [comment] 2022-09-28 11:14
Apologies, did not find the issue with search. This can be closed then.

**Comment by jokkebk** [comment] 2022-09-28 11:14
Apologies, did not find the issue with search. This can be closed then.

**Closed** 2022-09-28 11:57 UTC
Labels: bug
